theme: jekyll-theme-minimal
title: Alana Jaskir
description: PhD Candidate in Cognitive Science
Brown University
Department of Cognitive, Linguistic, and Psychological Sciences (CLPS)
Carney Institute for Brain Science
